# Generated by Django 6.0.3 on 2026-03-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
