# Generated by Django 6.0.3 on 2026-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('hr', 'HR'), ('teamlead', 'Team Lead'), ('employee', 'Employee'), ('manager', 'Manager')], default='employee', max_length=20),
        ),
    ]
